-- vim.api.nvim_clear_autocmds({ "BufFilePost", "BufEnter", "BufWinEnter", "LspAttach" }, {
--    group = vim.api.nvim_create_augroup("GoLoad", { clear = true }),
--    callback = function() end,
-- })
