
# Base config below

shell:
  program: /usr/local/bin/zsh
  args:
    - -l

draw_bold_text_with_bright_colors: true
live_config_reload: true

cursor:
  style: Block

window:
  dimensions:
    columns: 187
    lines: 53
  padding:
    x: 16
    y: 16
  dynamic_padding: true
  decorations: buttonless

scrolling:
  history: 100000

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Medium Italic
  bold_italic:
    family: Victor Mono
    style: Bold Italic
  size: 12.0
  offset:
    x: 0
    y: 4

bell:
  duration: 0
