[tool]

[tool.black]
exclude = '( /( \.eggs | \.git | \.hg | \.mypy_cache | \.pytest_cache | \.tox | _build | buck-out | build | dist)/ )'
include = '\.pyi?$'
target-version = ['py38']

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
