[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
formatter = { command = "fish", args = [
  "-c",
  "ruff check --fix - | ruff format -",
] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]
language-servers = ["marksman", "markdownlint-cli2"]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true
