vim.api.nvim_set_keymap("i", ",", ",<C-g>u", {noremap = true})
vim.api.nvim_set_keymap("i", ".", ".<C-g>u", {noremap = true})
vim.api.nvim_set_keymap("i", "!", "!<C-g>u", {noremap = true})
vim.api.nvim_set_keymap("i", "?", "?<C-g>u", {noremap = true})
vim.api.nvim_set_keymap("i", "#", "X#", {noremap = true})
vim.api.nvim_set_keymap("i", "<C-h>", "<BS>", {noremap = false})
