#!/usr/bin/env python3
from subprocess import run


DEF_NAME = "Filip Godlewski"
DEF_MAIL = "filip.godlewski@outlook.com"


def main():
    name = input(f"local name [{DEF_NAME}]: ") or DEF_NAME
    mail = input(f"local mail [{DEF_MAIL}]: ") or DEF_MAIL
    run(f"git config --local user.name '{name}'", shell=True)
    run(f"git config --local user.email '{mail}'", shell=True)


if __name__ == "__main__":
    main()
