#!/bin/zsh
set -e
trap 'rm -f "$$.tags"' EXIT
current_venv="$(pyenv prefix)"
if [[ "${$(pyenv prefix)##*/}" = "$(pyenv global)" ]]; then
    site_packages="$(rg ${PWD} --files -g '*.py' --color never)"
else
    site_packages="$(rg ${PWD} --files -g '*.py' --color never)"
    site_packages+="\n"
    site_packages+="$(rg ${current_venv}/**/site-packages --files -g '*.py' --color never)"
fi
echo $site_packages | ctags --tag-relative -L - -f "$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
