#!/bin/zsh
set -e
trap 'rm -f "$$.tags"' EXIT
current_venv="$(pyenv prefix)"
if [[ "${$(pyenv prefix)##*/}" = "$(pyenv global)" ]]; then
    site_packages="$(find ${PWD}**/*(.))"
else
    site_packages="$(find ${PWD}**/*(.))"
    site_packages+="\n"
    site_packages+="$(find ${current_venv}/**/site-packages/**/*.py)"
fi
echo $site_packages | ctags --tag-relative -L - -f "$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
