#! /usr/bin/env fish

set -l choices \
    "feat      # new feature" \
    "fix       # bug fix" \
    "refactor  # neutral change" \
    "test      # add/fix tests" \
    "docs      # documentation only" \
    "style     # formatting" \
    "chore     # no src, nor test related" \
    "perf      # improves performance" \
    "build     # build system or external deps" \
    "ci        # ci configs or scripts" \
    "revert    # previous commit"
set -l choice (gum choose $choices)

if test -z $choice
    echo "Nothing selected"
    return 130
end
set -l msg (echo $choice | string match --regex '^\w*')

set -l scope (gum input --placeholder "scope for `$msg`?")
if test -n $scope
    set msg "$msg($scope)"
end

test (gum confirm "Is `$msg` a breaking change?")
and set msg "$msg!"

set -l summary (gum input --value "$msg: " --header "Summary of this change" --char-limit=100)

gum confirm "Commit changes?" && git commit -m "$summary" || echo "Typed message:\n$summary"
