#!/usr/bin/env python3
import argparse
import os
import sys
from subprocess import DEVNULL, run

from pyfzf.pyfzf import FzfPrompt

DIRS = {
    "nvim": "share/nvim/site/pack/plugins/start",
    "tmux": "share/tmux",
    "zsh": "share/zsh/plugins",
    "other": "share/other"
}


def get_dirs_help():
    dirs = ", ".join(DIRS.keys())
    return f"Possible arguments: {dirs}"


def main(args):
    local = os.path.expanduser(f"~/dotfiles/{args.folder}/.local")
    sub_args = {"shell": True, "cwd": local, "capture_output": DEVNULL}
    folder = DIRS.get(args.folder, None)
    plugin_dirs = os.listdir(os.path.join(local, folder))
    fzf = FzfPrompt()
    try:
        names = fzf.prompt(plugin_dirs, "--multi --cycle")
    except Exception:
        sys.stderr.write("Aborted.\n")
        sys.exit(130)
    for name in names:
        path = os.path.join(folder, name)
        run(f"git submodule deinit -f {path}", **sub_args)
        run(f"git rm -rf {path}", **sub_args)
        run(f"git rm -rf {path}", **sub_args)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--folder", "-f", help=get_dirs_help(), required=True)
    args = parser.parse_args()
    main(args)
