#! /usr/bin/env zsh

set -e

files=$(git ls -dmok --exclude-standard --deduplicate --full-name)
selected_files=$(\
  echo $files \
    | sort \
    | gum filter --no-limit --fuzzy --header="Select files to commit"\
)
git add ${(@f)selected_files}

# vim:ft=zsh
