local s = vim.opt
local g = vim.g

g.mapleader = " "
g.python3_host_prog = vim.fn.expand("~/.local/share/venvs/nvim/bin/python3")

s.autowriteall = true
s.complete = s.complete + "kspell"
s.completeopt = {"menuone", "noinsert", "noselect"}
s.confirm = true
s.copyindent = true
s.cursorline = true
s.diffopt = {"filler", "vertical"}
s.expandtab = true
s.fileformat = "unix"
s.grepformat = "%f:%l:%c:%m"
s.grepprg = "rg --vimgrep --no-heading --case-sensitive --follow --word-regexp"
s.hidden = true
s.ignorecase = true
s.joinspaces = false
s.lazyredraw = true
s.matchpairs = s.matchpairs + "<:>"
s.mouse = "i"
s.nrformats = s.nrformats + "alpha"
s.path = s.path + "**"
s.pumblend = 30
s.pumheight = 10
s.shell = "/usr/local/bin/zsh"
s.shiftround = true
s.shiftwidth = 2
s.showmode = false
s.signcolumn = "yes"
s.smartcase = true
s.smartindent = true
s.softtabstop = 2
s.startofline = false
s.swapfile = false
s.syntax = "enable"
s.termguicolors = true
s.updatetime = 50
s.wildignore = s.wildignore + {"*.swp", "*.bak"}  -- temporary files
s.wildignore = s.wildignore + {"*.tar.*", "*.zip*"}  -- packages
s.wildignore = s.wildignore + {"*/.git/**/*", "*/.hg/**/*", "*/.svn/**/*"}  -- VCS
s.wildignore = s.wildignore + {"__*__", "*.pyc", "*.egg-info", "*/.pytest_cache/**/*"}  -- python
s.wildignore = s.wildignore + {"tags", "tags.*"}  -- ctags
s.wildignorecase = true
s.wildmode = {"longest:full", "full"}

vim.cmd("au FocusGained,WinEnter,BufEnter * checktime")
